# 指定我们的基础镜像是node
FROM registry.cn-hangzhou.aliyuncs.com/icamdora/nodejs:lts

# 设置工作目录 /usr/src/app
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# 添加 编译环境.build-deps
RUN apk add --no-cache --virtual .build-deps python make g++ gcc

# 配置环境变量
ONBUILD ARG NODE_ENV=production
ONBUILD ENV NODE_ENV $NODE_ENV

ONBUILD ARG PORT=3000
ONBUILD ENV PORT $PORT

ONBUILD ARG YARN_OR_NPM=npm

# 容器对外暴露的端口号
ONBUILD EXPOSE $PORT

# 安装项目依赖包
ONBUILD COPY package.json .npmr[c] /usr/src/app/
ONBUILD RUN $YARN_OR_NPM install --production --build-from-source && $YARN_OR_NPM cache clean --force

# 拷贝当前目录到 /usr/src/app
ONBUILD COPY . /usr/src/app

# 删除 .npmrc
ONBUILD RUN if [ -f .npmrc ]; then rm -f .npmrc; fi

# 删除 编译环境.build-deps
ONBUILD RUN apk del .build-deps

# 容器启动时执行的命令，类似npm run start
CMD ["node", "--version"]