# 指定我们的基础镜像是node
FROM registry.cn-hangzhou.aliyuncs.com/icamdora/nodejs:lts

# 设置工作目录 /usr/src/app
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# 添加 git
RUN apk add --no-cache --virtual .base-deps git

# 配置环境变量
ONBUILD ENV SASS_BINARY_SITE https://npm.taobao.org/mirrors/node-sass/

ONBUILD ARG NODE_ENV=production
ONBUILD ENV NODE_ENV $NODE_ENV

ONBUILD ARG PORT=3000
ONBUILD ENV PORT $PORT

ONBUILD ARG YARN_OR_NPM=yarn

# 容器对外暴露的端口号
ONBUILD EXPOSE $PORT

# 安装项目依赖包
ONBUILD COPY package.json .npmr[c] /usr/src/app/
ONBUILD RUN $YARN_OR_NPM install --production && $YARN_OR_NPM cache clean --force

# 拷贝当前目录到 /usr/src/app
ONBUILD COPY . /usr/src/app

# 删除 .npmrc
ONBUILD RUN if [ -f .npmrc ]; then rm -f .npmrc; fi

# 容器启动时执行的命令，类似npm run start
CMD ["node", "--version"]